[phases.setup]
nixPkgs = ["python3", "ffmpeg"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install --upgrade yt-dlp", "pip install -r requirements.txt"]

[start]
cmd = "python3 anything.py"
